CREATE DATABASE BT5;
USE BT5;

CREATE TABLE USERS (
    UserID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE WALLET (
    WalletID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT NOT NULL UNIQUE,
    Balance DECIMAL(15,2) NOT NULL DEFAULT 0 CHECK (Balance >= 0),
    FOREIGN KEY (UserID) REFERENCES USERS(UserID)
);

CREATE TABLE TRANSACTIONS (
    TransactionID INT PRIMARY KEY AUTO_INCREMENT,
    WalletID INT NOT NULL,
    TransactionType VARCHAR(20) NOT NULL CHECK (TransactionType IN ('DEPOSIT','WITHDRAW','PAYMENT')),
    Amount DECIMAL(15,2) NOT NULL CHECK (Amount > 0),
    TransactionDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Status VARCHAR(20) NOT NULL CHECK (Status IN ('PENDING','SUCCESS','FAILED')),
    FOREIGN KEY (WalletID) REFERENCES WALLET(WalletID)
);

